apiVersion: apps/v1
kind: Deployment 
metadata:
  name: javaapp-deployment
spec:
  selector:
    matchLabels:
      app: javaapp
  replicas: 2 
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      imagePullSecrets:
        - name: ecr-key
      containers:
        - name: javaapp
          image: 209479277669.dkr.ecr.ap-south-1.amazonaws.com/sept-2024:CI-CD
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster


---

apiVersion: v1 
kind: Service 
metadata: 
  name: javaapp-ssvc
spec:
  selector:
    app: javaapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80 
  type: LoadBalancer # type of the service.
